repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff-check  # Run the linter and fix issues.
        args: [ --fix ]
      - id: ruff-format  # Run the formatter.
      - id: ruff-check  # Run the linter after formatting.

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
