repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff-format  # Run the formatter.
        files: ^src/
      - id: ruff-check  # Run the linter
        args: [ --fix ]
        files: ^src/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
