# Site settings
site_name: FSIO Documentation
site_url: https://collier-p-charlie.github.io/fsio/

# Repository settings
repo_name: collier-p-charlie/fsio
repo_url: https://github.com/collier-p-charlie/fsio


# Theme settings
theme:
  name: material
  language: en
  font:
    text: montserrat
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - codehilite
  - toc:
      permalink: true

nav:
  - Home: index.md
  - API Reference:
      - Core: code/core/api.md
      - CLI: code/cli/api.md
  - Back to Homepage: "https://collier-p-charlie.github.io/"
